### ISSUE TITLE
Verify if the pwm is working correctly

### ISSUE THREAD

**Issue by SpectreDev-007** [folkhack/raspberry-pi-pwm-fan-2#2]
I can see the fan is spinning but i dont know if PWM is working correctly or not, is there a way to check Live RPMs or verify its working as intended

**Comment by folkhack** [comment]
Yes - there is support for a tachometer and it is documented both in the build instructions to compile a debug version of the binary, as well as the environment configuration.

Please read the project documentation for features before opening issues asking if they're included.
